// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package com.ruyuan2020.im.common.protobuf;

public final class CommandProto {
  private CommandProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan2020_im_Command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan2020_im_Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCommand.proto\022\021com.ruyuan2020.im\"E\n\007Co" +
      "mmand\022\014\n\004type\030\001 \001(\r\022\016\n\006userId\030\002 \001(\004\022\016\n\006c" +
      "lient\030\003 \001(\r\022\014\n\004body\030\004 \001(\014B3\n!com.ruyuan2" +
      "020.im.common.protobufB\014CommandProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ruyuan2020_im_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ruyuan2020_im_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan2020_im_Command_descriptor,
        new java.lang.String[] { "Type", "UserId", "Client", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
