// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package com.ruyuan2020.im.common.protobuf;

public interface CommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan2020.im.Command)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 type = 1;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>uint64 userId = 2;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>uint32 client = 3;</code>
   * @return The client.
   */
  int getClient();

  /**
   * <code>bytes body = 4;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
