// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageAckRequest.proto

package com.ruyuan2020.im.common.protobuf;

public final class MessageAckRequestProto {
  private MessageAckRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan2020_im_MessageAckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan2020_im_MessageAckRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027MessageAckRequest.proto\022\021com.ruyuan202" +
      "0.im\"Z\n\021MessageAckRequest\022\020\n\010chatType\030\001 " +
      "\001(\r\022\016\n\006chatId\030\002 \001(\004\022\020\n\010memberId\030\003 \001(\004\022\021\n" +
      "\tmessageId\030\004 \001(\004B=\n!com.ruyuan2020.im.co" +
      "mmon.protobufB\026MessageAckRequestProtoP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ruyuan2020_im_MessageAckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ruyuan2020_im_MessageAckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan2020_im_MessageAckRequest_descriptor,
        new java.lang.String[] { "ChatType", "ChatId", "MemberId", "MessageId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
