// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageFetch.proto

package com.ruyuan2020.im.common.protobuf;

public final class MessageFetchProto {
  private MessageFetchProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan2020_im_MessageFetch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan2020_im_MessageFetch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MessageFetch.proto\022\021com.ruyuan2020.im\"" +
      ">\n\014MessageFetch\022\016\n\006chatId\030\001 \001(\004\022\014\n\004toId\030" +
      "\002 \001(\004\022\020\n\010chatType\030\003 \001(\rB8\n!com.ruyuan202" +
      "0.im.common.protobufB\021MessageFetchProtoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ruyuan2020_im_MessageFetch_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ruyuan2020_im_MessageFetch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan2020_im_MessageFetch_descriptor,
        new java.lang.String[] { "ChatId", "ToId", "ChatType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
