// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageSendResponse.proto

package com.ruyuan2020.im.common.protobuf;

public final class MessageSendResponseProto {
  private MessageSendResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan2020_im_MessageSendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan2020_im_MessageSendResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031MessageSendResponse.proto\022\021com.ruyuan2" +
      "020.im\"\215\001\n\023MessageSendResponse\022\021\n\tmessag" +
      "eId\030\001 \001(\004\022\020\n\010chatType\030\002 \001(\r\022\016\n\006fromId\030\003 " +
      "\001(\004\022\014\n\004toId\030\004 \001(\004\022\020\n\010sequence\030\005 \001(\004\022\021\n\tt" +
      "imestamp\030\006 \001(\004\022\016\n\006chatId\030\007 \001(\004B?\n!com.ru" +
      "yuan2020.im.common.protobufB\030MessageSend" +
      "ResponseProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ruyuan2020_im_MessageSendResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ruyuan2020_im_MessageSendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan2020_im_MessageSendResponse_descriptor,
        new java.lang.String[] { "MessageId", "ChatType", "FromId", "ToId", "Sequence", "Timestamp", "ChatId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
