// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageFetch.proto

package com.ruyuan2020.im.common.protobuf;

/**
 * Protobuf type {@code com.ruyuan2020.im.MessageFetch}
 */
public final class MessageFetch extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ruyuan2020.im.MessageFetch)
    MessageFetchOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageFetch.newBuilder() to construct.
  private MessageFetch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageFetch() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageFetch();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageFetch(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            chatId_ = input.readUInt64();
            break;
          }
          case 16: {

            toId_ = input.readUInt64();
            break;
          }
          case 24: {

            chatType_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ruyuan2020.im.common.protobuf.MessageFetchProto.internal_static_com_ruyuan2020_im_MessageFetch_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ruyuan2020.im.common.protobuf.MessageFetchProto.internal_static_com_ruyuan2020_im_MessageFetch_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ruyuan2020.im.common.protobuf.MessageFetch.class, com.ruyuan2020.im.common.protobuf.MessageFetch.Builder.class);
  }

  public static final int CHATID_FIELD_NUMBER = 1;
  private long chatId_;
  /**
   * <code>uint64 chatId = 1;</code>
   * @return The chatId.
   */
  @java.lang.Override
  public long getChatId() {
    return chatId_;
  }

  public static final int TOID_FIELD_NUMBER = 2;
  private long toId_;
  /**
   * <code>uint64 toId = 2;</code>
   * @return The toId.
   */
  @java.lang.Override
  public long getToId() {
    return toId_;
  }

  public static final int CHATTYPE_FIELD_NUMBER = 3;
  private int chatType_;
  /**
   * <code>uint32 chatType = 3;</code>
   * @return The chatType.
   */
  @java.lang.Override
  public int getChatType() {
    return chatType_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (chatId_ != 0L) {
      output.writeUInt64(1, chatId_);
    }
    if (toId_ != 0L) {
      output.writeUInt64(2, toId_);
    }
    if (chatType_ != 0) {
      output.writeUInt32(3, chatType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (chatId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, chatId_);
    }
    if (toId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, toId_);
    }
    if (chatType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, chatType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ruyuan2020.im.common.protobuf.MessageFetch)) {
      return super.equals(obj);
    }
    com.ruyuan2020.im.common.protobuf.MessageFetch other = (com.ruyuan2020.im.common.protobuf.MessageFetch) obj;

    if (getChatId()
        != other.getChatId()) return false;
    if (getToId()
        != other.getToId()) return false;
    if (getChatType()
        != other.getChatType()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHATID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getChatId());
    hash = (37 * hash) + TOID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getToId());
    hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getChatType();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ruyuan2020.im.common.protobuf.MessageFetch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ruyuan2020.im.common.protobuf.MessageFetch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ruyuan2020.im.common.protobuf.MessageFetch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ruyuan2020.im.common.protobuf.MessageFetch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ruyuan2020.im.common.protobuf.MessageFetch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ruyuan2020.im.common.protobuf.MessageFetch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ruyuan2020.im.common.protobuf.MessageFetch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ruyuan2020.im.common.protobuf.MessageFetch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ruyuan2020.im.common.protobuf.MessageFetch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ruyuan2020.im.common.protobuf.MessageFetch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ruyuan2020.im.common.protobuf.MessageFetch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ruyuan2020.im.common.protobuf.MessageFetch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ruyuan2020.im.common.protobuf.MessageFetch prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ruyuan2020.im.MessageFetch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ruyuan2020.im.MessageFetch)
      com.ruyuan2020.im.common.protobuf.MessageFetchOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ruyuan2020.im.common.protobuf.MessageFetchProto.internal_static_com_ruyuan2020_im_MessageFetch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ruyuan2020.im.common.protobuf.MessageFetchProto.internal_static_com_ruyuan2020_im_MessageFetch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ruyuan2020.im.common.protobuf.MessageFetch.class, com.ruyuan2020.im.common.protobuf.MessageFetch.Builder.class);
    }

    // Construct using com.ruyuan2020.im.common.protobuf.MessageFetch.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      chatId_ = 0L;

      toId_ = 0L;

      chatType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ruyuan2020.im.common.protobuf.MessageFetchProto.internal_static_com_ruyuan2020_im_MessageFetch_descriptor;
    }

    @java.lang.Override
    public com.ruyuan2020.im.common.protobuf.MessageFetch getDefaultInstanceForType() {
      return com.ruyuan2020.im.common.protobuf.MessageFetch.getDefaultInstance();
    }

    @java.lang.Override
    public com.ruyuan2020.im.common.protobuf.MessageFetch build() {
      com.ruyuan2020.im.common.protobuf.MessageFetch result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ruyuan2020.im.common.protobuf.MessageFetch buildPartial() {
      com.ruyuan2020.im.common.protobuf.MessageFetch result = new com.ruyuan2020.im.common.protobuf.MessageFetch(this);
      result.chatId_ = chatId_;
      result.toId_ = toId_;
      result.chatType_ = chatType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ruyuan2020.im.common.protobuf.MessageFetch) {
        return mergeFrom((com.ruyuan2020.im.common.protobuf.MessageFetch)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ruyuan2020.im.common.protobuf.MessageFetch other) {
      if (other == com.ruyuan2020.im.common.protobuf.MessageFetch.getDefaultInstance()) return this;
      if (other.getChatId() != 0L) {
        setChatId(other.getChatId());
      }
      if (other.getToId() != 0L) {
        setToId(other.getToId());
      }
      if (other.getChatType() != 0) {
        setChatType(other.getChatType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ruyuan2020.im.common.protobuf.MessageFetch parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ruyuan2020.im.common.protobuf.MessageFetch) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long chatId_ ;
    /**
     * <code>uint64 chatId = 1;</code>
     * @return The chatId.
     */
    @java.lang.Override
    public long getChatId() {
      return chatId_;
    }
    /**
     * <code>uint64 chatId = 1;</code>
     * @param value The chatId to set.
     * @return This builder for chaining.
     */
    public Builder setChatId(long value) {
      
      chatId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 chatId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatId() {
      
      chatId_ = 0L;
      onChanged();
      return this;
    }

    private long toId_ ;
    /**
     * <code>uint64 toId = 2;</code>
     * @return The toId.
     */
    @java.lang.Override
    public long getToId() {
      return toId_;
    }
    /**
     * <code>uint64 toId = 2;</code>
     * @param value The toId to set.
     * @return This builder for chaining.
     */
    public Builder setToId(long value) {
      
      toId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 toId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearToId() {
      
      toId_ = 0L;
      onChanged();
      return this;
    }

    private int chatType_ ;
    /**
     * <code>uint32 chatType = 3;</code>
     * @return The chatType.
     */
    @java.lang.Override
    public int getChatType() {
      return chatType_;
    }
    /**
     * <code>uint32 chatType = 3;</code>
     * @param value The chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatType(int value) {
      
      chatType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 chatType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatType() {
      
      chatType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan2020.im.MessageFetch)
  }

  // @@protoc_insertion_point(class_scope:com.ruyuan2020.im.MessageFetch)
  private static final com.ruyuan2020.im.common.protobuf.MessageFetch DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ruyuan2020.im.common.protobuf.MessageFetch();
  }

  public static com.ruyuan2020.im.common.protobuf.MessageFetch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageFetch>
      PARSER = new com.google.protobuf.AbstractParser<MessageFetch>() {
    @java.lang.Override
    public MessageFetch parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageFetch(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageFetch> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageFetch> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ruyuan2020.im.common.protobuf.MessageFetch getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

