// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageAckRequest.proto

package com.ruyuan2020.im.common.protobuf;

public interface MessageAckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan2020.im.MessageAckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 chatType = 1;</code>
   * @return The chatType.
   */
  int getChatType();

  /**
   * <code>uint64 chatId = 2;</code>
   * @return The chatId.
   */
  long getChatId();

  /**
   * <code>uint64 memberId = 3;</code>
   * @return The memberId.
   */
  long getMemberId();

  /**
   * <code>uint64 messageId = 4;</code>
   * @return The messageId.
   */
  long getMessageId();
}
