// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagePush.proto

package com.ruyuan2020.im.common.protobuf;

public interface MessagePushOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan2020.im.MessagePush)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 chatType = 1;</code>
   * @return The chatType.
   */
  int getChatType();

  /**
   * <code>uint64 messageId = 2;</code>
   * @return The messageId.
   */
  long getMessageId();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>uint64 sequence = 4;</code>
   * @return The sequence.
   */
  long getSequence();

  /**
   * <code>uint64 timestamp = 5;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>uint64 chatId = 6;</code>
   * @return The chatId.
   */
  long getChatId();

  /**
   * <code>uint64 fromId = 7;</code>
   * @return The fromId.
   */
  long getFromId();

  /**
   * <code>uint64 memberId = 8;</code>
   * @return The memberId.
   */
  long getMemberId();

  /**
   * <code>uint32 messageType = 9;</code>
   * @return The messageType.
   */
  int getMessageType();
}
