// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageSendRequest.proto

package com.ruyuan2020.im.common.protobuf;

public interface MessageSendRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan2020.im.MessageSendRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 messageId = 1;</code>
   * @return The messageId.
   */
  long getMessageId();

  /**
   * <code>uint32 chatType = 2;</code>
   * @return The chatType.
   */
  int getChatType();

  /**
   * <code>uint64 fromId = 3;</code>
   * @return The fromId.
   */
  long getFromId();

  /**
   * <code>uint64 toId = 4;</code>
   * @return The toId.
   */
  long getToId();

  /**
   * <code>uint64 chatId = 5;</code>
   * @return The chatId.
   */
  long getChatId();

  /**
   * <code>uint32 messageType = 6;</code>
   * @return The messageType.
   */
  int getMessageType();

  /**
   * <code>string content = 7;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 7;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>uint64 sequence = 8;</code>
   * @return The sequence.
   */
  long getSequence();

  /**
   * <code>uint64 timestamp = 9;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
