// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineRequest.proto

package com.ruyuan2020.im.common.protobuf;

public final class OnlineRequestProto {
  private OnlineRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan2020_im_OnlineRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan2020_im_OnlineRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023OnlineRequest.proto\022\021com.ruyuan2020.im" +
      "\"\036\n\rOnlineRequest\022\r\n\005token\030\001 \001(\tB9\n!com." +
      "ruyuan2020.im.common.protobufB\022OnlineReq" +
      "uestProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ruyuan2020_im_OnlineRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ruyuan2020_im_OnlineRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan2020_im_OnlineRequest_descriptor,
        new java.lang.String[] { "Token", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
