// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineRequest.proto

package com.ruyuan2020.im.common.protobuf;

public interface OnlineRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan2020.im.OnlineRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
