server:
  port: 8097
spring:
  profiles:
    active: dev
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  application:
    name: account
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.50.210:3306/im_dev?useSSL=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: abc.1234
      filters: stat
      maxActive: 200
      initialSize: 50
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      asyncInit: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.210:8848
        namespace: ruyuan-im-dev
  redis:
    host: 192.168.50.210
    port: 6379
    password: abc.1234
    timeout: 10000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 2
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  cloud:
    subscribed-services: ''
  protocol:
    name: dubbo
    port: 28097
  provider:
    threads: 800